// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'age': string;
  'audioInfo': string;
  'audioInfoPopover': string;
  'audioPreference': string;
  'audioPreferenceLabel': string;
  'audioScore': string;
  'audioTrack': string;
  'audioTrackList': string;
  'audioTrackTag': string;
  'blocklist': string;
  'customFormatScore': string;
  'download': string;
  'downloadIcon': string;
  'history': string;
  'indexer': string;
  'indexerFlags': string;
  'interactiveIcon': string;
  'languages': string;
  'manualDownloadContent': string;
  'mediaCellContent': string;
  'mediaLoadingIcon': string;
  'peers': string;
  'protocol': string;
  'quality': string;
  'rejected': string;
  'selectedAudio': string;
  'size': string;
  'subs': string;
  'titleContent': string;
}
export const cssExports: CssExports;
export default cssExports;
