// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'actionsCell': string;
  'arrayHeader': string;
  'buttonContent': string;
  'checkboxCell': string;
  'checkboxField': string;
  'checkboxList': string;
  'checkboxListItem': string;
  'compactInput': string;
  'emptyState': string;
  'field': string;
  'formGrid': string;
  'formTable': string;
  'formTableScroller': string;
  'input': string;
  'nameCell': string;
  'rowButtonCell': string;
  'scoreInput': string;
  'sectionToolbar': string;
  'table': string;
  'tableScroller': string;
  'textArea': string;
}
export const cssExports: CssExports;
export default cssExports;
