// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'actionsCell': string;
  'addCard': string;
  'arrayHeader': string;
  'buttonContent': string;
  'cardCheckbox': string;
  'cardGrid': string;
  'cardInput': string;
  'cardTitle': string;
  'cardTitleContainer': string;
  'center': string;
  'checkboxCell': string;
  'checkboxField': string;
  'checkboxList': string;
  'checkboxListItem': string;
  'compactInput': string;
  'configCard': string;
  'editableCard': string;
  'editableCardHeader': string;
  'emptyState': string;
  'field': string;
  'formGrid': string;
  'formTable': string;
  'formTableScroller': string;
  'input': string;
  'inputList': string;
  'inputListItem': string;
  'label': string;
  'labels': string;
  'leftButtons': string;
  'nameCell': string;
  'pickerPanel': string;
  'rowButtonCell': string;
  'scoreInput': string;
  'sectionToolbar': string;
  'table': string;
  'tableScroller': string;
  'textArea': string;
}
export const cssExports: CssExports;
export default cssExports;
