// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addMutexGroup': string;
  'buttons': string;
  'center': string;
  'checkboxField': string;
  'checkboxList': string;
  'checkboxListItem': string;
  'customFormatMutexGroups': string;
  'field': string;
  'formGrid': string;
  'iconButton': string;
  'input': string;
  'label': string;
  'labels': string;
  'mutexGroupCard': string;
  'name': string;
  'nameContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
