// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'addCard': string;
  'cardGrid': string;
  'cardTitle': string;
  'cardTitleContainer': string;
  'center': string;
  'checkboxField': string;
  'childList': string;
  'conditionCard': string;
  'conditionGrid': string;
  'conditionHeader': string;
  'configCard': string;
  'emptyState': string;
  'field': string;
  'formGrid': string;
  'groupActions': string;
  'groupCard': string;
  'groupControls': string;
  'groupHeader': string;
  'input': string;
  'label': string;
  'labels': string;
  'rootGroup': string;
  'valuePlaceholder': string;
}
export const cssExports: CssExports;
export default cssExports;
